repos:
  - repo: https://github.com/ambv/black
    rev: 21.8b0
    hooks:
      - id: black
        name: black
        language: python
        types: [python]
        description: "Black: The uncompromising Python code formatter"
        # language_version: python3.9
        files: \.(py)$
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        files: \.(py)$
