"""init

Revision ID: 29f3e3aaae5b
Revises:
Create Date: 2021-11-18 19:21:18.627686

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "29f3e3aaae5b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("repo_url", sa.VARCHAR(), nullable=False),
        sa.Column("on_prem", sa.Boolean(), nullable=True),
        sa.Column("lead_name", sa.VARCHAR(), nullable=True),
        sa.Column("lead_email", sa.VARCHAR(), nullable=True),
        sa.Column("description", sa.VARCHAR(), nullable=True),
        sa.Column("location", sa.VARCHAR(), nullable=True),
        sa.Column("github_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column(
            "project_auth_token_hashed",
            sa.VARCHAR(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_id"), "project", ["id"], unique=False)
    op.create_table(
        "workitem",
        sa.Column("category", sa.VARCHAR(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("failed", sa.Boolean(), nullable=True),
        sa.Column("comments", sa.VARCHAR(), nullable=True),
        sa.Column("issue_num", sa.Integer(), nullable=True),
        sa.Column("duration_open", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workitem_id"), "workitem", ["id"], unique=False)
    op.create_table(
        "commit",
        sa.Column("sha", sa.VARCHAR(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("message", sa.VARCHAR(), nullable=True),
        sa.Column("author", sa.VARCHAR(), nullable=True),
        sa.Column("work_item_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time_to_pull", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["workitem.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_commit_id"), "commit", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_commit_id"), table_name="commit")
    op.drop_table("commit")
    op.drop_index(op.f("ix_workitem_id"), table_name="workitem")
    op.drop_table("workitem")
    op.drop_index(op.f("ix_project_id"), table_name="project")
    op.drop_table("project")
    # ### end Alembic commands ###
