"""first migration

Revision ID: 1d3daaeebc36
Revises: 
Create Date: 2021-05-14 03:12:44.918520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1d3daaeebc36"
down_revision = None
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_meetings_meetingId", table_name="meetings")
    op.drop_table("meetings")
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meetings",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("meetingId", sa.VARCHAR(), nullable=False),
        sa.Column("date", sa.VARCHAR(), nullable=True),
        sa.Column("employeeNumber", sa.NUMERIC(precision=3, scale=0), nullable=True),
        sa.Column("time", sa.NUMERIC(precision=3, scale=0), nullable=True),
        sa.Column("totalCost", sa.NUMERIC(precision=7, scale=2), nullable=True),
        sa.Column("powerpoint", sa.BOOLEAN(), nullable=True),
        sa.Column("comment", sa.VARCHAR(), nullable=True),
        sa.Column("title", sa.VARCHAR(), nullable=True),
        sa.Column("powerpointSlides", sa.NUMERIC(precision=3, scale=0), nullable=True),
        sa.CheckConstraint("powerpoint IN (0, 1)"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_meetings_id", "meetings", ["id"], unique=True)
    # ### end Alembic commands ###
