# Runs Unit Test on every committ

name: Backend Unit Tests

# on: push
on: workflow_dispatch

jobs:
  backend-unit-tests:
      uses: rropen/reusable-workflows/.github/workflows/pytest.yml@main
      with:
        testing_directory: src/backend/tests
