name: deploy_github_pages

on: workflow_dispatch

jobs:
    backend-unit-tests:
      uses: rropen/reusable-workflows/.github/workflows/deploy_github_pages.yml@main
      with:
        vue_directory: src/backend
        build_folder: dist
      secrets: 
        vue_cobalt_token: ${{ secrets.VUE_COBALT_PAT }}
