name: Development Build
# on:
#   pull_request:
#     branches: [dev]

#   push:
#     branches: [dev]

on: workflow_dispatch

jobs:
  Deploy-Dev:
    runs-on: ubuntu-latest
    steps:
    
     - name: Checkout repository
       uses: actions/checkout@v2
       
     - uses: azure/docker-login@v1
       with:
        login-server: ${{ secrets.CRSFT_LOGIN_SERVER }}
        username: ${{ secrets.CRSFT_USERNAME}}
        password: ${{ secrets.CRSFT_PASSWORD }}
     - run: |
          docker build -t crsft.azurecr.us/sfm_backend_dev:latest src/backend
          docker push crsft.azurecr.us/sfm_backend_dev:latest
    
