# DANGER
# Quickly deploys to Azure with no testing or scanning

name: Fast Deploy

on: workflow_dispatch

jobs:
  frontend-build-deploy-azure:
  runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CRSFT_LOGIN_SERVER }}
          username: ${{ secrets.CRSFT_USERNAME}}
          password: ${{ secrets.CRSFT_PASSWORD }}
      - name: Build/Push Frontend Container
        run: |
          docker build --build-arg NODE_AUTH_TOKEN=${{ secrets.VUE_COBALT_PAT }} -t ${{ secrets.IMAGE_FRONTEND_DEV }} src/frontend
          docker push ${{ secrets.IMAGE_FRONTEND_DEV }}
        env:
          NODE_ENV: production
          VITE_MODE: production
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_API_AUTH_TOKEN: ${{ secrets.VITE_API_AUTH_TOKEN }}
    backend-build-deply-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CRSFT_LOGIN_SERVER }}
          username: ${{ secrets.CRSFT_USERNAME}}
          password: ${{ secrets.CRSFT_PASSWORD }}
      - name: Build/Push Frontend Container
        run: |
          docker build --build-arg NODE_AUTH_TOKEN=${{ secrets.VUE_COBALT_PAT }} -t ${{ secrets.IMAGE_FRONTEND_DEV }} src/frontend
          docker push ${{ secrets.IMAGE_FRONTEND_DEV }}
        env:
          NODE_ENV: production
          VITE_MODE: production
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_API_AUTH_TOKEN: ${{ secrets.VITE_API_AUTH_TOKEN }}
