name: Integration Tests
on:
  #   workflow_run:
  #     workflows: ["Backend Unit Tests", "Frontend Unit Tests"]
  #     branches: dev
  #     types: completed

  pull_request:
    branches: main
  push:
    branches: dev

jobs:
  # Runs Integration Tests w/ Cypress
  Integration-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Configure Backend Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

      - name: Install Backend Dependencies
        working-directory: src/backend
        run: |
          python -m pip install --upgrade pip pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Backend
        working-directory: src/backend
        env:
          ENV: test
          DEBUG: False
          TESTING: True
          SECRET_KEY: secret_key
          ADMIN_KEY: admin_key
          FRONTEND_URL: http://localhost:3000
        run: |
          python -m uvicorn sfm.main:app --port 8181 &

      - name: Setup Frontend
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@rrglobal"

      - name: Configure Frontend Cache (1/2)
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Configure Frontend Cache (2/2)
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Frontend Dependencies
        working-directory: src/frontend
        run: yarn --prefer-offline
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VUE_COBALT_PAT }}

      - name: Cypress Integration Tests
        working-directory: src/frontend
        env:
          VITE_API_URL: "http://localhost:8181"
        run: |
          yarn cy
