name: Production Build

on: workflow_dispatch

jobs:
  backend-build-deploy-azure:
    uses: rropen/reusable-workflows/.github/workflows/docker_deploy_azure.yml@main
    with:
      dockerfile_directory: src/backend
      GH_image: ghcr.io/rropen/sfm_backend:latest
    secrets:
      AZ_image: ${{ secrets.IMAGE_BACKEND_PROD }}
      crsft_login_server: ${{ secrets.CRSFT_LOGIN_SERVER }}
      crsft_username: ${{ secrets.CRSFT_USERNAME }}
      crsft_password: ${{ secrets.CRSFT_PASSWORD }}
      cr_username: ${{ secrets.GH_CR_USERNAME }}
      cr_PAT: ${{ secrets.CONTAINER_PAT }}

  frontend-build-deploy-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CRSFT_LOGIN_SERVER }}
          username: ${{ secrets.CRSFT_USERNAME}}
          password: ${{ secrets.CRSFT_PASSWORD }}
      - name: Build/Push Frontend Container
        run: |
          docker build --build-arg NODE_AUTH_TOKEN=${{ secrets.VUE_COBALT_PAT }} -t ${{ secrets.IMAGE_FRONTEND_PROD }} src/frontend
          docker push ${{ secrets.IMAGE_FRONTEND_PROD }}
